"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import s from "../tournament.module.css";

type M={id:string;match_number:number;scheduled_at:string|null;court:number|null;status:string;team_a:{name:string}|null;team_b:{name:string}|null};

export default function Schedule(){
 const[id,setId]=useState("");const[date,setDate]=useState("");const[start,setStart]=useState("09:00");const[courts,setCourts]=useState("2");const[duration,setDuration]=useState("20");const[rest,setRest]=useState("5");const[matches,setMatches]=useState<M[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>setId(new URLSearchParams(window.location.search).get("id")||""),[]);
 async function load(){if(!id)return;const{data,error}=await supabase.from("tournament_matches").select("id,match_number,scheduled_at,court,status,team_a:tournament_duos!tournament_matches_team_a_duo_id_fkey(name),team_b:tournament_duos!tournament_matches_team_b_duo_id_fkey(name)").eq("tournament_id",id).order("match_number");if(error)setError(error.message);setMatches((data||[])as any)}
 useEffect(()=>{load()},[id]);
 async function generate(){if(!date)return setError("Choose a schedule date.");if(!matches.length)return setError("Generate the draw first.");setBusy(true);setError("");const base=new Date(`${date}T${start}:00`);const c=Math.max(1,Number(courts));const dur=Math.max(1,Number(duration));const gap=Math.max(0,Number(rest));for(let i=0;i<matches.length;i++){const slot=Math.floor(i/c);const court=(i%c)+1;const when=new Date(base.getTime()+slot*(dur+gap)*60000);const{error}=await supabase.from("tournament_matches").update({scheduled_at:when.toISOString(),court}).eq("id",matches[i].id);if(error){setError(error.message);setBusy(false);return}}const{error:e}=await supabase.from("tournament_schedules").upsert({tournament_id:id,schedule_date:date,start_at:base.toISOString(),court_count:c,match_duration_minutes:dur,rest_minutes:gap,status:"PUBLISHED",updated_at:new Date().toISOString()},{onConflict:"tournament_id"});if(e)setError(e.message);await load();setBusy(false)}
 const path=(p:string)=>`/tournaments/${p}?id=${encodeURIComponent(id)}`;
 if(!id)return <main className={s.page}><div className={s.shell}><div className={s.card}>Tournament ID is missing.</div></div></main>;
 return <main className={s.page}><div className={s.shell}><div className={s.brand}>SCHEDULE</div><h1 className={s.title}>Courts & match times</h1><p className={s.sub}>Generate a practical running order from the current draw.</p><div className={s.card}><div className={s.grid}><div className={s.field}><label>Date</label><input className={s.input} type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className={s.field}><label>Start time</label><input className={s.input} type="time" value={start} onChange={e=>setStart(e.target.value)}/></div><div className={s.field}><label>Courts</label><input className={s.input} type="number" min="1" value={courts} onChange={e=>setCourts(e.target.value)}/></div><div className={s.field}><label>Match duration (min)</label><input className={s.input} type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)}/></div><div className={s.field}><label>Rest between slots (min)</label><input className={s.input} type="number" min="0" value={rest} onChange={e=>setRest(e.target.value)}/></div></div><button className={s.button} disabled={busy} onClick={generate}>{busy?"Scheduling…":"Generate schedule"}</button>{error&&<div className={s.error}>{error}</div>}</div><div className={s.card}><h2>Match order</h2><div className={s.list}>{matches.map(m=><div className={s.item} key={m.id}><div><strong>Match {m.match_number}</strong><div>{m.team_a?.name||"TBD"} <span className={s.muted}>vs</span> {m.team_b?.name||"TBD"}</div></div><div style={{textAlign:"right"}}><span className={s.pill}>Court {m.court||"—"}</span><div className={s.muted}>{m.scheduled_at?new Date(m.scheduled_at).toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"}):"Not scheduled"}</div></div></div>)}</div></div><div className={s.footerActions}><Link href={path("draw")} className={s.button+" "+s.secondary}>Back</Link><Link href={path("manage")} className={s.button}>Tournament dashboard →</Link></div></div></main>;
}
