"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { supabase } from "../../../lib/supabase";
import s from "../tournament.module.css";

type Tournament={id:string;name:string;start_date:string|null}; type Round={id:string;name:string|null;round_number:number|null;round_type:string|null}; type Duo={id:string;name:string|null}; type Match={id:string;round_id:string|null;match_number:number|null;court:number|null;scheduled_at:string|null;status:string|null;team_a_duo_id:string|null;team_b_duo_id:string|null;team_a_score:number|null;team_b_score:number|null};
export default function TournamentSchedulePage(){
 const params=useSearchParams(); const tournamentId=params.get("id"); const[tournament,setTournament]=useState<Tournament|null>(null);const[rounds,setRounds]=useState<Round[]>([]);const[matches,setMatches]=useState<Match[]>([]);const[duos,setDuos]=useState<Duo[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{if(!tournamentId){setError("Tournament id is missing.");setLoading(false);return}let cancelled=false;(async()=>{const[t,r,m,d]=await Promise.all([supabase.from("tournaments").select("id,name,start_date").eq("id",tournamentId).single(),supabase.from("tournament_rounds").select("id,name,round_number,round_type").eq("tournament_id",tournamentId).order("round_number"),supabase.from("tournament_matches").select("id,round_id,match_number,court,scheduled_at,status,team_a_duo_id,team_b_duo_id,team_a_score,team_b_score").eq("tournament_id",tournamentId).order("match_number"),supabase.from("tournament_duos").select("id,name").eq("tournament_id",tournamentId)]);if(cancelled)return;const e=t.error||r.error||m.error||d.error;if(e)setError(e.message);setTournament(t.data);setRounds(r.data||[]);setMatches(m.data||[]);setDuos(d.data||[]);setLoading(false)})();return()=>{cancelled=true}},[tournamentId]);
 const duoName=useMemo(()=>new Map(duos.map(d=>[d.id,d.name||"TBD"])),[duos]); const path=(p:string)=>`/tournaments/${p}?id=${encodeURIComponent(tournamentId||"")}`; const groups=rounds.map(r=>({r,m:matches.filter(x=>x.round_id===r.id)})).filter(x=>x.m.length); const ungrouped=matches.filter(m=>!m.round_id); const time=(v:string|null)=>v?new Date(v).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"TBD";
 if(loading)return <main className={s.page}><div className={s.shell}><div className={s.card}>Loading schedule…</div></div></main>;
 return <main className={s.page}><div className={s.shell}><div className={s.top}><div><div className={s.brand}>RALLY365 · {tournament?.name||"TOURNAMENT"}</div><h1 className={s.title}>Schedule</h1><p className={s.sub}>{tournament?.start_date?new Date(tournament.start_date).toLocaleDateString():"Date TBD"} · Complete match plan</p></div><Link href={path("manage")} className={s.secondaryButton}>← Overview</Link></div><nav className={s.tabs}><Link className={s.tab} href={path("manage")}>Overview</Link><Link className={`${s.tab} ${s.tabActive}`} href={path("schedule")}>Schedule</Link><Link className={s.tab} href={path("matches")}>Live matches</Link><Link className={s.tab} href={path("standings")}>Standings</Link></nav>{error&&<div className={s.error}>{error}</div>}{!error&&!matches.length&&<section className={s.card}><h2>No matches yet</h2><p className={s.sub}>Generate the draw first.</p><Link href={path("draw")} className={s.button} style={{marginTop:12}}>Go to Draw</Link></section>}{groups.map(({r,m})=><section className={s.card} key={r.id}><div className={s.sectionHeader}><div><div className={s.eyebrow}>ROUND {r.round_number??""}</div><h2>{r.name||`${r.round_type||"Round"}`}</h2></div><span>{m.length} matches</span></div><div className={s.grid2}>{m.map(x=><Link className={s.matchTile} key={x.id} href={`/tournaments/match?id=${x.id}`} style={{textDecoration:"none",color:"inherit"}}><div className={s.matchTileTop}><span>Match {x.match_number??"—"}</span><span>{time(x.scheduled_at)} · {x.court?`Court ${x.court}`:"Court TBD"}</span></div><div className={s.teamLine}><span className={s.teamIdentity}><span className={s.avatar}>A</span><span className={s.teamName}>{duoName.get(x.team_a_duo_id||"")||"TBD"}</span></span><span className={s.teamScore}>{x.team_a_score??"-"}</span></div><div className={s.teamLine}><span className={s.teamIdentity}><span className={s.avatar}>B</span><span className={s.teamName}>{duoName.get(x.team_b_duo_id||"")||"TBD"}</span></span><span className={s.teamScore}>{x.team_b_score??"-"}</span></div><div className={s.matchTileTop}><span>{x.status||"SCHEDULED"}</span><span>›</span></div></Link>)}</div></section>)}{ungrouped.length>0&&<section className={s.card}><h2>Unassigned matches</h2>{ungrouped.map(x=><Link key={x.id} className={s.matchTile} href={`/tournaments/match?id=${x.id}`} style={{display:"block",textDecoration:"none",color:"inherit",marginTop:8}}>Match {x.match_number} · {duoName.get(x.team_a_duo_id||"")||"TBD"} vs {duoName.get(x.team_b_duo_id||"")||"TBD"}</Link>)}</section>}</div></main>;
}
