"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";
import s from "../tournament.module.css";

type T={id:string;name:string;venue:string|null;start_date:string|null;format:string;partner_mode:string;status:string};
type M={id:string;match_number:number;scheduled_at:string|null;court:number|null;status:string;team_a_score:number|null;team_b_score:number|null;team_a_duo_id:string|null;team_b_duo_id:string|null;team_a:{name:string}|null;team_b:{name:string}|null};
const label=(v:string)=>({KNOCKOUT:"Doubles Knockout",ROUND_ROBIN:"Round Robin",GROUPS_KNOCKOUT:"Groups + Knockout",RANDOM_ROUNDS:"Random Rounds"}as Record<string,string>)[v]||v.replaceAll("_"," ");
const date=(v:string|null)=>v?new Date(v).toLocaleDateString("en-IN",{month:"short",day:"numeric",year:"numeric"}):"Date TBD";
function countdown(v:string|null){if(!v)return ["--","--","--","--"];const diff=Math.max(0,new Date(v).getTime()-Date.now());const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),sec=Math.floor(diff%60000/1000);return [String(d).padStart(2,"0"),String(h).padStart(2,"0"),String(m).padStart(2,"0"),String(sec).padStart(2,"0")]}
export default function Dashboard(){
 const[id,setId]=useState("");const[t,setT]=useState<T|null>(null);const[matches,setMatches]=useState<M[]>([]);const[counts,setCounts]=useState({players:0,teams:0,matches:0,completed:0});const[error,setError]=useState("");const[now,setNow]=useState(Date.now());
 useEffect(()=>setId(new URLSearchParams(window.location.search).get("id")||""),[]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!id)return;(async()=>{const[tr,pr,dr,mr]=await Promise.all([supabase.from("tournaments").select("id,name,venue,start_date,format,partner_mode,status").eq("id",id).single(),supabase.from("tournament_players").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("tournament_duos").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("tournament_matches").select("id,match_number,scheduled_at,court,status,team_a_score,team_b_score,team_a_duo_id,team_b_duo_id,team_a:tournament_duos!tournament_matches_team_a_duo_id_fkey(name),team_b:tournament_duos!tournament_matches_team_b_duo_id_fkey(name)").eq("tournament_id",id).order("match_number")]);if(tr.error){setError(tr.error.message);return}setT(tr.data);setCounts({players:pr.count||0,teams:dr.count||0,matches:mr.data?.length||0,completed:(mr.data||[]).filter(x=>x.status==="COMPLETED").length});setMatches((mr.data||[])as any)})()},[id]);
 const path=(p:string)=>`/tournaments/${p}?id=${encodeURIComponent(id)}`;const upcoming=matches.filter(m=>m.status!=="COMPLETED").slice(0,4);const cd=countdown(t?.start_date||null);void now;
 if(error)return <main className={s.page}><div className={s.shell}><div className={s.error}>{error}</div></div></main>;
 if(!id)return <main className={s.page}><div className={s.shell}><div className={s.card}>Loading tournament…</div></div></main>;
 return <main className={s.page}><div className={s.shell}>
  <div className={s.mobileTournamentHeader}><Link href="/tournaments" className={s.iconBack}>‹</Link><strong>{t?.name||"Rally365 Open"}</strong><span className={s.menuDots}>⋮</span></div>
  <section className={s.tournamentHero}><div><div className={s.brand} style={{color:"#d9d07a"}}>RALLY365 OPEN</div><h1>{t?.name||"Rally365 Open"}</h1><p>📅 {date(t?.start_date||null)} &nbsp; · &nbsp; 📍 {t?.venue||"Venue TBD"}</p></div><span className={s.statusBadge}>{t?.status||"UPCOMING"}</span></section>
  <nav className={s.tabs}><Link className={`${s.tab} ${s.tabActive}`} href={path("manage")}>Overview</Link><Link className={s.tab} href={path("draw")}>Draw</Link><Link className={s.tab} href={path("matches")}>Matches</Link><Link className={s.tab} href={path("standings")}>Standings</Link><Link className={s.tab} href={path("players")}>Players</Link></nav>
  <section className={s.card}><div className={s.eyebrow}>TOURNAMENT STARTS IN</div><div className={s.countdown}>{cd.map((v,i)=><div key={i}><strong>{v}</strong><span>{["Days","Hours","Minutes","Seconds"][i]}</span></div>)}</div></section>
  <div className={s.overviewStats}><div className={s.overviewStat}><strong>⚙</strong><span>{label(t?.format||"")}</span></div><div className={s.overviewStat}><strong>{counts.teams}</strong><span>Duos</span></div><div className={s.overviewStat}><strong>₹0</strong><span>Entry fee</span></div><div className={s.overviewStat}><strong>🏸</strong><span>Organized by Rally365</span></div></div>
  <section className={s.card} style={{marginTop:14}}><div className={s.sectionHeader}><div><div className={s.eyebrow}>NEXT UP</div><h2>Match schedule</h2></div><Link href={path("draw")} className={s.secondaryButton}>View draw →</Link></div><div className={s.grid2}>{upcoming.map(m=><Link key={m.id} href={`/tournaments/match?id=${m.id}`} className={s.matchTile}><div className={s.matchTileTop}><span>Match {m.match_number}</span><span>{m.scheduled_at?new Date(m.scheduled_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"Time TBD"}</span></div><div className={s.teamLine}><span className={s.teamIdentity}><span className={s.avatar}>A</span><span className={s.teamName}>{m.team_a?.name||"TBD"}</span></span><strong className={s.teamScore}>{m.team_a_score??"-"}</strong></div><div className={s.teamLine}><span className={s.teamIdentity}><span className={s.avatar}>B</span><span className={s.teamName}>{m.team_b?.name||"TBD"}</span></span><strong className={s.teamScore}>{m.team_b_score??"-"}</strong></div></Link>)}</div>{!upcoming.length&&<p className={s.sub}>No matches generated yet.</p>}</section>
  <div className={s.grid2} style={{marginTop:14}}><Link href={path("draw")} className={s.button}>View draw →</Link><Link href={path("players")} className={`${s.button} ${s.secondary}`}>View players</Link></div>
 </div></main>;
}
