"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import s from "../tournament.module.css";

type T={id:string;name:string;venue:string|null;start_date:string|null;format:string;partner_mode:string;status:string};
type M={id:string;match_number:number;scheduled_at:string|null;court:number|null;status:string;team_a_score:number|null;team_b_score:number|null;team_a_duo_id:string|null;team_b_duo_id:string|null;team_a:{name:string}|null;team_b:{name:string}|null};
const label=(v:string)=>({KNOCKOUT:"Doubles Knockout",ROUND_ROBIN:"Round Robin",GROUPS_KNOCKOUT:"Groups + Knockout",RANDOM_ROUNDS:"Random Rounds"}as Record<string,string>)[v]||v.replaceAll("_"," ");
const date=(v:string|null)=>v?new Date(v).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"Date TBD";

export default function Dashboard(){
 const[id,setId]=useState(""); const[t,setT]=useState<T|null>(null); const[matches,setMatches]=useState<M[]>([]); const[counts,setCounts]=useState({players:0,teams:0,matches:0,completed:0}); const[error,setError]=useState("");
 useEffect(()=>setId(new URLSearchParams(window.location.search).get("id")||""),[]);
 useEffect(()=>{if(!id)return;(async()=>{const [tr,pr,dr,mr]=await Promise.all([supabase.from("tournaments").select("id,name,venue,start_date,format,partner_mode,status").eq("id",id).single(),supabase.from("tournament_players").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("tournament_duos").select("id",{count:"exact",head:true}).eq("tournament_id",id),supabase.from("tournament_matches").select("id,match_number,scheduled_at,court,status,team_a_score,team_b_score,team_a_duo_id,team_b_duo_id,team_a:tournament_duos!tournament_matches_team_a_duo_id_fkey(name),team_b:tournament_duos!tournament_matches_team_b_duo_id_fkey(name)").eq("tournament_id",id).order("match_number",{ascending:true})]); if(tr.error){setError(tr.error.message);return} setT(tr.data);setCounts({players:pr.count||0,teams:dr.count||0,matches:mr.data?.length||0,completed:(mr.data||[]).filter(x=>x.status==="COMPLETED").length});setMatches((mr.data||[])as any)})()},[id]);
 const path=(p:string)=>`/tournaments/${p}?id=${encodeURIComponent(id)}`;
 if(error)return <main className={s.page}><div className={s.shell}><div className={s.error}>{error}</div></div></main>;
 if(!id)return <main className={s.page}><div className={s.shell}><div className={s.card}>Loading tournament…</div></div></main>;
 const upcoming=matches.filter(m=>m.status!=="COMPLETED").slice(0,3);
 return <main className={s.page}><div className={s.shell}>
   <div className={s.top}><Link href="/tournaments" className={s.secondaryButton}>← Tournaments</Link><span className={s.pill}>{t?.status||"UPCOMING"}</span></div>
   <section className={s.tournamentHero}><div><div className={s.brand} style={{color:"#d9c26a"}}>RALLY365 OPEN</div><h1>{t?.name||"Tournament"}</h1><p>📅 {date(t?.start_date||null)} &nbsp; · &nbsp; 📍 {t?.venue||"Venue TBD"}</p></div><span className={s.statusBadge}>{t?.status||"UPCOMING"}</span></section>
   <div className={s.tournamentMeta}><div className={s.metaBox}><strong>👥 {counts.players} Players</strong><span>Individual entries</span></div><div className={s.metaBox}><strong>🤝 {counts.teams} Duos</strong><span>Partner teams</span></div><div className={s.metaBox}><strong>🏸 {counts.matches} Matches</strong><span>{counts.completed} completed</span></div></div>
   <nav className={s.tabs}><Link className={`${s.tab} ${s.tabActive}`} href={path("manage")}>Overview</Link><Link className={s.tab} href={path("draw")}>Draw</Link><Link className={s.tab} href={path("matches")}>Matches</Link><Link className={s.tab} href={path("standings")}>Standings</Link><Link className={s.tab} href={path("players")}>Players</Link></nav>
   <section className={s.hero}><div className={s.eyebrow} style={{color:"#bfead7"}}>TOURNAMENT FORMAT</div><h2>{label(t?.format||"")}</h2><p>{t?.partner_mode === "FIXED" ? "Fixed partners" : "Random partners"} · {counts.teams} teams ready. Generate the draw, then use Matches to run the event live.</p></section>
   <div className={s.overviewStats}><div className={s.overviewStat}><strong>{counts.players}</strong><span>Players</span></div><div className={s.overviewStat}><strong>{counts.teams}</strong><span>Teams</span></div><div className={s.overviewStat}><strong>{counts.completed}</strong><span>Completed</span></div><div className={s.overviewStat}><strong>{Math.max(0,counts.matches-counts.completed)}</strong><span>Remaining</span></div></div>
   <section className={s.card} style={{marginTop:14}}><div className={s.sectionHeader}><div><div className={s.eyebrow}>NEXT UP</div><h2>Match schedule</h2></div><Link href={path("schedule")} className={s.secondaryButton}>View all →</Link></div>{upcoming.length?<div className={s.grid2}>{upcoming.map(m=><Link key={m.id} href={`/tournaments/match?id=${m.id}`} style={{textDecoration:"none",color:"inherit"}}><div className={s.matchTile}><div className={s.matchTileTop}><span>Match {m.match_number}</span><span>{m.scheduled_at?new Date(m.scheduled_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"Time TBD"} · {m.court?`Court ${m.court}`:"Court TBD"}</span></div><div className={s.teamLine}><span className={s.teamIdentity}><span className={s.avatar}>A</span><span className={s.teamName}>{m.team_a?.name||"TBD"}</span></span><span className={s.teamScore}>{m.team_a_score??"-"}</span></div><div className={s.teamLine}><span className={s.teamIdentity}><span className={s.avatar}>B</span><span className={s.teamName}>{m.team_b?.name||"TBD"}</span></span><span className={s.teamScore}>{m.team_b_score??"-"}</span></div></div></Link>)}</div>:<p className={s.sub}>No matches generated yet. Go to Draw to create the competition schedule.</p>}</section>
   <div className={s.grid2} style={{marginTop:14}}><Link href={path("draw")} className={s.card} style={{textDecoration:"none",color:"inherit"}}><div className={s.eyebrow}>STEP 01</div><h3>Build the draw</h3><p className={s.sub}>Create groups, round robin, knockout or random rounds.</p></Link><Link href={path("players")} className={s.card} style={{textDecoration:"none",color:"inherit"}}><div className={s.eyebrow}>STEP 02</div><h3>Manage players</h3><p className={s.sub}>Add or remove tournament-specific participants.</p></Link></div>
 </div></main>;
}
