"use client";

import Link from "next/link";import {useParams} from "next/navigation";import {useEffect,useState} from "react";import {supabase} from "../../../../lib/supabase";import {randomPairs} from "../../../../lib/tournament";import s from "../../tournament.module.css";
type P={id:string;name:string};type D={id:string;name:string;source:string;locked:boolean;members:{player_id:string;slot:number;player?:P}[]};
export default function Partners(){const {id}=useParams<{id:string}>();const [players,setPlayers]=useState<P[]>([]);const [duos,setDuos]=useState<D[]>([]);const [mode,setMode]=useState("RANDOM");const [fixed,setFixed]=useState<string[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const [{data:p},{data:d,error:e}]=await Promise.all([supabase.from("tournament_players").select("id,name").eq("tournament_id",id).order("name"),supabase.from("tournament_duos").select("id,name,source,locked,tournament_duo_members(player_id,slot)").eq("tournament_id",id).order("created_at")]);if(e)setError(e.message);setPlayers(p||[]);const rows=(d||[]) as any[];setDuos(rows.map(x=>({...x,members:(x.tournament_duo_members||[]).map((m:any)=>({...m,player:(p||[]).find((q:P)=>q.id===m.player_id)}))})))} useEffect(()=>{load()},[id]);
 async function clearDraft(){await supabase.from("tournament_duo_members").delete().in("duo_id",duos.map(d=>d.id));await supabase.from("tournament_duos").delete().eq("tournament_id",id)}
 async function generateRandom(){if(players.length<2)return setError("Add at least two players.");setBusy(true);setError("");await clearDraft();for(const pair of randomPairs(players)){const names=pair.map(p=>p.name);const {data:d,error:e}=await supabase.from("tournament_duos").insert({tournament_id:id,name:names.join(" + "),source:"RANDOM",locked:false}).select("id").single();if(e||!d){setError(e?.message||"Could not create pair");break}await supabase.from("tournament_duo_members").insert(pair.map((p,i)=>({duo_id:d.id,player_id:p.id,slot:i+1})))}await load();setBusy(false)}
 async function addFixed(){if(fixed.length!==2)return setError("Select exactly two players.");setBusy(true);const pair=fixed.map(x=>players.find(p=>p.id===x)!).filter(Boolean);const {data:d,error:e}=await supabase.from("tournament_duos").insert({tournament_id:id,name:pair.map(p=>p.name).join(" + "),source:"FIXED",locked:false}).select("id").single();if(e||!d)setError(e?.message||"Could not create pair");else await supabase.from("tournament_duo_members").insert(pair.map((p,i)=>({duo_id:d.id,player_id:p.id,slot:i+1})));setFixed([]);await load();setBusy(false)}
 async function lock(){if(!duos.length)return;const {error:e}=await supabase.from("tournament_duos").update({locked:true}).eq("tournament_id",id);if(e)setError(e.message);else load()}
 return <main className={s.page}><div className={s.shell}><div className={s.brand}>PARTNERS</div><h1 className={s.title}>Build tournament pairs</h1><p className={s.sub}>Choose random partners or create already-fixed pairs. Nothing here depends on Rally365's normal duos.</p><div className={s.tabs}><button className={s.tab+(mode==="RANDOM"?" "+s.tabActive:"")} onClick={()=>setMode("RANDOM")}>Random partners</button><button className={s.tab+(mode==="FIXED"?" "+s.tabActive:"")} onClick={()=>setMode("FIXED")}>Already fixed partners</button></div>{mode==="RANDOM"?<div className={s.card}><h2>Generate random partners</h2><p className={s.muted}>The player list is shuffled and paired. If the count is odd, the last player remains unpaired for the next setup decision.</p><button className={s.button} disabled={busy} onClick={generateRandom}>{busy?"Generating…":"Generate / regenerate pairs"}</button></div>:<div className={s.card}><h2>Create a fixed pair</h2><div className={s.grid2}><div className={s.list}>{players.map(p=><label className={s.check} key={p.id}><input type="checkbox" checked={fixed.includes(p.id)} disabled={fixed.length===2&&!fixed.includes(p.id)} onChange={e=>setFixed(v=>e.target.checked?[...v,p.id]:v.filter(x=>x!==p.id))}/>{p.name}</label>)}</div><div><div className={s.hero}><div className={s.metric}>{fixed.length}/2</div><div className={s.muted}>selected</div></div><button className={s.button} disabled={busy||fixed.length!==2} onClick={addFixed}>Add fixed pair</button></div></div></div>}{error&&<div className={s.error}>{error}</div>}<div className={s.card} style={{marginTop:18}}><div className={s.row}><h2>Current pairs</h2><button className={s.button+" "+s.secondary} onClick={lock} disabled={!duos.length}>Lock partners</button></div><div className={s.list}>{duos.map((d,i)=><div className={s.item} key={d.id}><div><strong>{i+1}. {d.name}</strong><div className={s.muted}>{d.source} · {d.locked?"Locked":"Draft"}</div></div></div>)}{!duos.length&&<p className={s.muted}>No pairs created yet.</p>}</div></div><div className={s.footerActions}><Link href={`/tournaments/${id}/players`} className={s.button+" "+s.secondary}>Back</Link><Link href={`/tournaments/${id}/draw`} className={s.button}>Continue to draw →</Link></div></div></main>}
