"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import s from "../tournament.module.css";

type M={id:string;match_number:number;team_a_score:number;team_b_score:number;status:string;scheduled_at:string|null;court:number|null;team_a_duo_id:string|null;team_b_duo_id:string|null;winner_duo_id:string|null;team_a:{name:string}|null;team_b:{name:string}|null};

export default function MatchDetail(){
 const[id,setId]=useState("");const[matchId,setMatchId]=useState("");const[m,setM]=useState<M|null>(null);const[a,setA]=useState("0");const[b,setB]=useState("0");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setId(q.get("id")||"");setMatchId(q.get("matchId")||"")},[]);
 useEffect(()=>{if(!id||!matchId)return;(async()=>{const{data,error}=await supabase.from("tournament_matches").select("id,match_number,team_a_score,team_b_score,status,scheduled_at,court,team_a_duo_id,team_b_duo_id,winner_duo_id,team_a:tournament_duos!tournament_matches_team_a_duo_id_fkey(name),team_b:tournament_duos!tournament_matches_team_b_duo_id_fkey(name)").eq("id",matchId).eq("tournament_id",id).single();if(error)setError(error.message);else{setM(data as any);setA(String(data?.team_a_score??0));setB(String(data?.team_b_score??0))}})()},[id,matchId]);
 async function save(status:string){if(!m)return;setBusy(true);const na=Number(a),nb=Number(b);const winnerId=status==="COMPLETED"?(na>nb?m.team_a_duo_id:na<nb?m.team_b_duo_id:null):null;const{error}=await supabase.from("tournament_matches").update({team_a_score:na,team_b_score:nb,status,winner_duo_id:winnerId}).eq("id",m.id);if(error)setError(error.message);else setM({...m,team_a_score:na,team_b_score:nb,status,winner_duo_id:winnerId});setBusy(false)}
 if(!id||!matchId)return <main className={s.page}><div className={s.shell}><div className={s.card}>Match information is missing.</div></div></main>;
 return <main className={s.page}><div className={s.shell}><div className={s.brand}>MATCH CONTROL</div>{error?<div className={s.error}>{error}</div>:!m?<div className={s.card}>Loading match…</div>:<><h1 className={s.title}>Match {m.match_number}</h1><p className={s.sub}>{m.court?`Court ${m.court} · `:""}{m.scheduled_at?new Date(m.scheduled_at).toLocaleString("en-IN"):"Unscheduled"}</p><div className={s.hero}><div className={s.grid2}><div><h2>{m.team_a?.name||"TBD"}</h2><div className={s.big}>{a}</div><input className={s.input} type="number" min="0" value={a} onChange={e=>setA(e.target.value)}/></div><div><h2>{m.team_b?.name||"TBD"}</h2><div className={s.big}>{b}</div><input className={s.input} type="number" min="0" value={b} onChange={e=>setB(e.target.value)}/></div></div><div className={s.actions} style={{marginTop:20}}><button className={s.button} disabled={busy||!m.team_a_duo_id||!m.team_b_duo_id} onClick={()=>save("COMPLETED")}>Save completed result</button><button className={s.button+" "+s.secondary} disabled={busy} onClick={()=>save("LIVE")}>Mark live</button><button className={s.button+" "+s.danger} disabled={busy} onClick={()=>save("CANCELLED")}>Cancel match</button></div></div></>}<Link href={`/tournaments/matches?id=${encodeURIComponent(id)}`} className={s.button+" "+s.secondary}>← All matches</Link></div></main>;
}
